### ISSUE TITLE
Is Sec. 3.3 redundant?

### ISSUE THREAD

**Issue by tieguy** [tieguy/collabmark.org#19]
Frederik says:
"3.3: The whole section 3.3 sounds to my non-lawyer ear as if it was just reaffirming rights that you already have ... I would like to pre-face … the whole section 3.3 with something like "this section reaffirms rights that you would have even without this policy" or so."

Luis responds:
It's a little complicated, since you may have those rights in some places but not others, so in those places it is a good idea to list out the rights explicitly.

Would it work to say something like "3.3.6. Other legally permitted uses. You may also have these or other rights to use the mark, depending on the circumstances and the jurisdiction [place?] in which you are using those rights. This license is not intended to limit any rights you have under those legal doctrines."? (Probably not that exact language.)

**Comment by simonpoole** [comment]
"This license is not intended to limit any such rights" perhaps?  Otherwise fine with me.

**Comment by tieguy** [comment]
The more I think about it, the more I think stuffing it in 3.3.6 is not right. Might instead rewrite the section's lead to something like:

> You may use the non-stylized wordmarks (such as "OpenStreetMap") to factually name or refer to:
> (general examples).
> This use of our marks is called "nominative" or "referential" use, and may already be allowed by law in some legal systems. Specific examples of nominative/referential use include:

And then leave the examples unchanged.

@woodpeck does this address your concern?

**Comment by woodpeck** [comment]
Sounds good to me. "_May_ already be allowed by law in _some_ legal systems" has a bit of an undertone as if we wanted to distance us from them ("There _may_ be _some_ cultures where the concept of property does not exist..."). If it is likely that the reader is in a legal system where such use is allowed, we could be more bold ans say "is already allowed by law in many legal systems". But, details.

**Comment by tieguy** [comment]
It's in the EU and US, though inconsistently applied in both, hence the license language. Can't speak to the rest of the world, though it is a common-sense enough notion. (In the US and UK it is common-sense enough that it comes from the common law rather than statute.)

I'll commit "is already allowed by law in some legal systems" momentarily.
