### ISSUE TITLE
What mailing list should be used for notification in Sec. 7?

### ISSUE THREAD

**Issue by tieguy** [tieguy/collabmark.org#25]

**Comment by simonpoole** [comment]
IMHO for
- announcements announce@openstreetmap.org 
- discussion: talk@openstreetmap.org

**Comment by tieguy** [comment]
Thanks. Resolved in latest commit: https://github.com/tieguy/OSM-collabmark.org/commit/d24e68b9e8dc34d721689da466792250116ba2f1 

(need to get more used to how GitHub cross-tags these, sorry for inefficient linking...)
