### ISSUE TITLE
2.1 and adverbs

### ISSUE THREAD

**Issue by woodpeck** [tieguy/collabmark.org#29]
2.1 bullet point 1 is a bit idiosyncratic in that it goes into much grammatical detail ("you may use ... as proper name or as an adjective"). What about adverbial use ("You haven't done that very OpenStreetMappily I must say"), would that not be allowed? Perhaps find an easier wording that doesn't invite such nitpicking?

**Comment by simonpoole** [comment]
Just to make you happy :-) lets change the wording to ..or as an adjective or adverb ... At least in the languages that I'm relatively fluent in it does require mangling the trademark a bit though.

**Comment by tieguy** [comment]
Adverbial use, as Simon says, typically requires mangling and should not generally be permitted.
